import fs from 'node:fs';
import {launch,newCtx,load} from '../tooling/1to1/src/lib/browser.ts';
const browser=await launch(true),context=await newCtx(browser,{width:1440,height:900},2),page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const results:any={};
try {
 await load(page,'http://localhost:3781/user-authentication',1000);const card=page.getByRole('heading',{name:'Compliance',exact:true}).locator('../../..');await card.scrollIntoViewIfNeeded();await card.hover();await page.waitForTimeout(900);results.compliance=await card.locator('path[stroke="#5DE3FF"]').evaluateAll(nodes=>nodes.map(node=>({dash:(node as SVGElement).style.strokeDasharray,opacity:(node as SVGElement).style.opacity})));await page.screenshot({path:'reference/decorations-compliance.png'});
 await load(page,'http://localhost:3781/platform',750);const security=page.locator('div').filter({has:page.locator(':scope > [data-line]')});const selector='div[class*="size-[calc(120/16*1rem)]"]';await page.locator(selector).scrollIntoViewIfNeeded();await page.waitForTimeout(3500);results.platform=await page.locator(selector).evaluate(node=>({rays:[...node.children].filter(n=>(n as HTMLElement).style.transform.startsWith('rotate(')).length,arcs:node.querySelectorAll('svg[viewBox="0 0 120 120"]').length,rects:[...node.querySelectorAll('svg[viewBox="0 0 120 120"] g rect')].map(n=>n.getAttribute('x'))}));await page.screenshot({path:'reference/decorations-platform.png'});
 await load(page,'http://localhost:3781/billing',750);await page.locator('[data-plan]').scrollIntoViewIfNeeded();await page.waitForTimeout(3400);results.billing=await page.locator('[data-plan]').evaluate(node=>{const host=node.parentElement!;return{beamCanvas:host.querySelectorAll('[data-meteor] canvas').length,beamPaths:[...host.querySelectorAll('[data-meteor] svg path')].map(p=>p.getAttribute('d')),waveCanvas:host.querySelectorAll('[data-dots] canvas').length}});await page.screenshot({path:'reference/decorations-billing.png'});
 results.errors=errors;fs.writeFileSync('reference/decorations-runtime.json',JSON.stringify(results,null,2));console.log(results);
}finally{await browser.close()}
